name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.19
        ports:
          - 3306
        env:
          MYSQL_DATABASE: tracker_test
          MYSQL_USER: username
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: password

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew build
      - name: Chech mysql access
        run: |
          mysql --host 127.0.0.1 ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"
